### ISSUE TITLE
tmstore: study the impact of replacing broadcastTxCommit with the asynchronous version

### ISSUE THREAD

**Issue by such** [stratumn/go-core#215]
Does it help regarding Tendermint performance?
How do we emulate the current behaviour?

**Comment by such** [comment]
Apparently, `CheckTx` will be run anyway so in the general case it's safe to return the `Segment` to the user.

**Comment by simonvadee** [comment]
I made the change in https://github.com/stratumn/go-indigocore/commit/05a375e6d573b6a12e050b7c3af0362917f5b348

However, there is a bug with `Service.Restart()` in tendermint, which prevents us from going forward with this. I submitted an issue to their github which was closed because they will refactor te `service` api (see https://github.com/tendermint/tendermint/pull/1239).

I can still do some testing and will follow up on this.

**Comment by simonvadee** [comment]
Tendermint is currently refactoring the `Service` API which implies a few changes in our test architecture, I'll wait for https://github.com/tendermint/tmlibs/pull/114 to be merged before going further with this (not really prio n°1 ATM).

**Comment by t-bast** [comment]
Obsolete
